fos_rest:
    param_fetcher_listener: true
    allowed_methods_listener: true
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    exception:
        enabled: true
        exception_controller: 'App\Controller\ExceptionController::showAction'
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json }
