framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    serializer: ~
    templating: { engines: ['twig'] }
    #csrf_protection: true
    #http_method_override: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
