jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            root:
                namespace_prefix: "App\\Entity"
                path: "%kernel.project_dir%/serializer"
