App\Entity\Environment:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: int
            groups: ['state_view']
        title:
            expose: true
            type: string
            groups: ['state_view']